### ISSUE TITLE
Caught by controller[0]: Error: Cannot find module 'typescript' after update to 3.1.5

### ISSUE THREAD

**Issue by peterbaumert** [ioBroker/ioBroker.js-controller#929]
Updated to 3.1.5 and got this error:

`

host.iobroker | 2020-06-08 12:26:46.988 | error | instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2020-06-08 12:26:46.987 | error | Caught by controller[0]: }
host.iobroker | 2020-06-08 12:26:46.982 | error | Caught by controller[0]: ]
host.iobroker | 2020-06-08 12:26:46.982 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.javascript/main.js'
host.iobroker | 2020-06-08 12:26:46.981 | error | Caught by controller[0]: '/opt/iobroker/node_modules/virtual-tsc/build/index.js',
host.iobroker | 2020-06-08 12:26:46.980 | error | Caught by controller[0]: '/opt/iobroker/node_modules/virtual-tsc/build/compiler.js',
host.iobroker | 2020-06-08 12:26:46.979 | error | Caught by controller[0]: requireStack: [
host.iobroker | 2020-06-08 12:26:46.974 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2020-06-08 12:26:46.973 | error | Caught by controller[0]: {
host.iobroker | 2020-06-08 12:26:46.973 | error | Caught by controller[0]: at internal/main/run_main_module.js:17:47
host.iobroker | 2020-06-08 12:26:46.972 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
host.iobroker | 2020-06-08 12:26:46.971 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.iobroker | 2020-06-08 12:26:46.966 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
host.iobroker | 2020-06-08 12:26:46.965 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.iobroker | 2020-06-08 12:26:46.965 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.iobroker | 2020-06-08 12:26:46.964 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:35:24)
host.iobroker | 2020-06-08 12:26:46.963 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
host.iobroker | 2020-06-08 12:26:46.958 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
host.iobroker | 2020-06-08 12:26:46.958 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.iobroker | 2020-06-08 12:26:46.957 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
host.iobroker | 2020-06-08 12:26:46.956 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.iobroker | 2020-06-08 12:26:46.956 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.iobroker | 2020-06-08 12:26:46.950 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/virtual-tsc/build/index.js:3:18)
host.iobroker | 2020-06-08 12:26:46.950 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
host.iobroker | 2020-06-08 12:26:46.949 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
host.iobroker | 2020-06-08 12:26:46.949 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.iobroker | 2020-06-08 12:26:46.947 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
host.iobroker | 2020-06-08 12:26:46.946 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.iobroker | 2020-06-08 12:26:46.941 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.iobroker | 2020-06-08 12:26:46.940 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/virtual-tsc/build/compiler.js:3:10)
host.iobroker | 2020-06-08 12:26:46.939 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
host.iobroker | 2020-06-08 12:26:46.935 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
host.iobroker | 2020-06-08 12:26:46.932 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:842:27)
host.iobroker | 2020-06-08 12:26:46.931 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
host.iobroker | 2020-06-08 12:26:46.926 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.javascript/main.js
host.iobroker | 2020-06-08 12:26:46.926 | error | Caught by controller[0]: - /opt/iobroker/node_modules/virtual-tsc/build/index.js
host.iobroker | 2020-06-08 12:26:46.925 | error | Caught by controller[0]: - /opt/iobroker/node_modules/virtual-tsc/build/compiler.js
host.iobroker | 2020-06-08 12:26:46.924 | error | Caught by controller[0]: Require stack:
host.iobroker | 2020-06-08 12:26:46.924 | error | Caught by controller[0]: Error: Cannot find module 'typescript'
host.iobroker | 2020-06-08 12:26:46.923 | error | Caught by controller[0]: ^
host.iobroker | 2020-06-08 12:26:46.922 | error | Caught by controller[0]: throw err;
host.iobroker | 2020-06-08 12:26:46.921 | error | Caught by controller[0]: internal/modules/cjs/loader.js:969

`

KR
Pete

**Comment by cmorlok** [comment]
Same here. Reinstalling `iobroker.javascript` did not help, but manually installing `typescript` fixed it.

**Comment by Apollon77** [comment]
What was it for a system= proper setup with iobroker installer or what? There were some rare cases earlier or under WIndows where npm looses packages sometimes .... so question is about that.

Tried the installation fixer?

**Comment by cmorlok** [comment]
@Apollon77 in my case it was a quite fresh installation on a Raspi 4, following the official instructions to install on Raspbian.

I haven't tried to use the installation fixer as that one messed up my installation the last time I used it.

**Comment by Apollon77** [comment]
> following the official instructions to install on Raspbian.
Do you have the link?

**Comment by cmorlok** [comment]
> > following the official instructions to install on Raspbian.
> 
> Do you have the link?

https://www.iobroker.net/#de/documentation/install/linux.md

I just had a look. I did a clean install in November last year, and the last time I have upgraded iobroker was about 2 month ago.

**Comment by AlCalzone** [comment]
> After doing `npm install typescript` in iobroker dir it works again.

By the way, this is not the correct way to fix these kinds of issues. Go into the folder of the adapter which is missing its dependencies (here: javascript) and install its dependencies:
``` 
cd /opt/iobroker/node_modules/iobroker.javascript
npm install --production
```

Installing stuff in the root dir will cause unnecessary dependencies to linger around if the adapter updates its modules.

**Comment by cmorlok** [comment]
> > After doing `npm install typescript` in iobroker dir it works again.
> 
> By the way, this is not the correct way to fix these kinds of issues. Go into the folder of the adapter which is missing its dependencies (here: javascript) and install its dependencies:
> 
> ```
> cd /opt/iobroker/node_modules/iobroker.javascript
> npm install --production
> ```
> 
> Installing stuff in the root dir will cause unnecessary dependencies to linger around if the adapter updates its modules.

This is exactly what I tried first, but it did not solve the issue.

**Comment by AlCalzone** [comment]
@cmorlok Then maybe the same command in `/opt/iobroker/node_modules/virtual-tsc` (the module which tries to load typescript).
As long as the module is referenced somewhere, running `npm install --production` in the correct folder will install it.

**Comment by AlCalzone** [comment]
By the way, I just upgraded JS-Controller from 3.1.4 to 3.1.5 with no issues.

If you could provide **reproducible** steps that cause this issue, it would help us immensely in narrowing this down. E.g.
1. _install image xyz_ or _install with the script_
2. upgrade adapter abc
3. upgrade js-controller

**Comment by Homoran** [comment]
package-lock.json and package.json can be found in the forum:
https://forum.iobroker.net/topic/34206/nach-scriptausf%C3%BChrung-nur-noch-fehler-und-keine-funkion/11

**Comment by cmorlok** [comment]
@AlCalzone 

> @cmorlok Then maybe the same command in `/opt/iobroker/node_modules/virtual-tsc` (the module which tries to load typescript).
> As long as the module is referenced somewhere, running `npm install --production` in the correct folder will install it.

That's what did:

```
iobroker:/opt/iobroker/node_modules/virtual-tsc $ npm install --production
added 3 packages from 5 contributors and audited 423 packages in 30.339s
found 165 vulnerabilities (111 low, 1 moderate, 52 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

iobroker:/opt/iobroker/node_modules/virtual-tsc $ ls node_modules
colors  debug  ms

iobroker:/opt/iobroker/node_modules/iobroker.javascript $ npm install --production
> iobroker.javascript@4.6.17 postinstall /opt/iobroker/node_modules/iobroker.javascript
> node ./install/installTypings.js

Installing NodeJS typings...
latest @types: 14, installed node: 10
added 67 packages from 109 contributors and audited 669 packages in 48.647s
found 0 vulnerabilities

iobroker:/opt/iobroker/node_modules/iobroker.javascript $ ls node_modules
ajv          bcrypt-pbkdf     core-util-is       ecc-jsbn                    form-data       is-nan         json-schema-traverse  minimist         object-keys      safe-buffer             tough-cookie  uuid
asn1         caseless         cron-parser        extend                      getpass         isstream       json-stringify-safe   moment           performance-now  safer-buffer            tunnel-agent  verror
assert-plus  coffee-compiler  dashdash           extsprintf                  har-schema      is-typedarray  jsprim                moment-timezone  psl              semver                  tweetnacl     virtual-tsc
asynckit     coffee-script    debug              fast-deep-equal             har-validator   jsbn           long-timeout          ms               punycode         sorted-array-functions  @types        vm2
aws4         colors           define-properties  fast-json-stable-stringify  http-signature  jsonata        mime-db               node-schedule    qs               sshpk                   typescript    wake_on_lan
aws-sign2    combined-stream  delayed-stream     forever-agent               @iobroker       json-schema    mime-types            oauth-sign       request          suncalc2                uri-js

iobroker:/opt/iobroker/node_modules $ find -name typescript -type d
./virtual-tsc/node_modules.bak/typescript
./zigbee-herdsman/node_modules/typescript
./zigbee-herdsman-converters/node_modules/@babel/parser/lib/plugins/typescript
./socks/docs/examples/typescript
./iobroker.javascript/node_modules/typescript
./iobroker.javascript/admin/vs/language/typescript
./mqtt/test/typescript

iobroker:/opt/iobroker/node_modules $ for p in *; do jq -e .dependencies.typescript $p/package.json > /dev/null && echo -n $p/node_modules/typescript: && ls $p/node_modules/typescript; done
iobroker.javascript/node_modules/typescript:AUTHORS.md  bin  CODE_OF_CONDUCT.md  CopyrightNotice.txt  lib  LICENSE.txt  loc  package.json  README.md  ThirdPartyNoticeText.txt

iobroker:/opt/iobroker/node_modules $ for p in *; do jq -e .peerDependencies.typescript $p/package.json > /dev/null && echo -n $p/node_modules/typescript: && ls $p/node_modules/typescript; done
virtual-tsc/node_modules/typescript:ls: cannot access 'virtual-tsc/node_modules/typescript': No such file or directory
```



> By the way, I just upgraded JS-Controller from 3.1.4 to 3.1.5 with no issues.
> 
> If you could provide **reproducible** steps that cause this issue, it would help us immensely in narrowing this down.

Is there any way to get the logs of `iobroker upgrade self`? I have no idea which versions I was running before.

**Comment by AlCalzone** [comment]
> I did that as well, but `virtual-tsc` seems not to install `typescript`. It is listed as peerDependency, not as production dependency, and I don't know how the resolver works.

True... iobroker.javascript has typescript as a dependency, virtual-tsc has it as a peerDependency, which should be resolved to the one in the adapter.
Looking at your paths, the reason might be that `virtual-tsc` is hoisted to `/opt/iobroker/node_modules` by npm, but for some reason, `typescript` is not. I wonder why this is happening now after it worked for 2-3 years... 
Probably npm changed something under the hood.

I'll need to provide virtual-tsc with the correct path if it cannot find typescript - l look into it.

**Comment by AlCalzone** [comment]
Yup, this seems to be a known bug in npm... 🤮
https://npm.community/t/packages-with-peerdependencies-are-incorrectly-hoisted/4794
