### ISSUE TITLE
Changed write or readFile behavior leads to breaking changes

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.js-controller#2193]
**Describe the bug**
After updating hm-rega adapter to 3.0.46 (which fixes this issue https://github.com/ioBroker/ioBroker.hm-rega/issues/368) errors are shown in the log and adapter does not start

**To Reproduce**
1. Update hm-rega version to 3.0.46
2. Restart hm-rega instance
3. see error in the log

**Screenshots & Logfiles**
```
2023-03-31 20:24:26.962 - info: host.ioBrokerTestsystem Restart adapter system.adapter.hm-rega.0 because enabled
2023-03-31 20:24:45.993 - info: host.ioBrokerTestsystem instance system.adapter.hm-rega.0 started with pid 9827
2023-03-31 20:24:50.536 - info: hm-rega.0 (9827) starting. Version 3.0.46 in /opt/iobroker/node_modules/iobroker.hm-rega, node: v18.15.0, js-controller: 5.0.1-alpha.0-20230330-e0b409fe
2023-03-31 20:24:50.805 - info: hm-rega.0 (9827) [REGASCRIPTS] Successfully updated datapoints.fn
2023-03-31 20:24:50.878 - info: hm-rega.0 (9827) subscribe .BidCoS-RF.50.PRESS_SHORT
2023-03-31 20:24:50.960 - info: hm-rega.0 (9827) ReGaHSS 192.168.178.84 up
2023-03-31 20:24:51.093 - info: hm-rega.0 (9827) time difference local-ccu 0s
2023-03-31 20:24:53.315 - info: hm-rega.0 (9827) request state values
2023-03-31 20:24:53.327 - error: hm-rega.0 (9827) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-31 20:24:53.330 - error: hm-rega.0 (9827) unhandled promise rejection: this.pendingRequests[0].script.slice(...).replace is not a function
2023-03-31 20:24:53.346 - error: hm-rega.0 (9827) TypeError: this.pendingRequests[0].script.slice(...).replace is not a function
at Rega.script (/opt/iobroker/node_modules/iobroker.hm-rega/lib/rega.js:147:78)
at /opt/iobroker/node_modules/iobroker.hm-rega/lib/rega.js:108:22
at new Promise ()
at Rega.runScriptFile (/opt/iobroker/node_modules/iobroker.hm-rega/lib/rega.js:107:20)
at getDatapoints (/opt/iobroker/node_modules/iobroker.hm-rega/main.js:1376:16)
at Object.ready (/opt/iobroker/node_modules/iobroker.hm-rega/main.js:386:17)
2023-03-31 20:24:53.349 - error: hm-rega.0 (9827) this.pendingRequests[0].script.slice(...).replace is not a function
2023-03-31 20:24:53.594 - info: hm-rega.0 (9827) terminating
2023-03-31 20:24:53.600 - warn: hm-rega.0 (9827) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-31 20:24:53.895 - info: hm-rega.0 (9827) terminating
2023-03-31 20:24:54.330 - error: host.ioBrokerTestsystem Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-03-31 20:24:54.331 - error: host.ioBrokerTestsystem Caught by controller[0]: TypeError: this.pendingRequests[0].script.slice(...).replace is not a function
2023-03-31 20:24:54.333 - error: host.ioBrokerTestsystem Caught by controller[0]: at Rega.script (/opt/iobroker/node_modules/iobroker.hm-rega/lib/rega.js:147:78)
2023-03-31 20:24:54.334 - error: host.ioBrokerTestsystem Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.hm-rega/lib/rega.js:108:22
2023-03-31 20:24:54.335 - error: host.ioBrokerTestsystem Caught by controller[0]: at new Promise ()
2023-03-31 20:24:54.336 - error: host.ioBrokerTestsystem Caught by controller[0]: at Rega.runScriptFile (/opt/iobroker/node_modules/iobroker.hm-rega/lib/rega.js:107:20)
2023-03-31 20:24:54.337 - error: host.ioBrokerTestsystem Caught by controller[0]: at getDatapoints (/opt/iobroker/node_modules/iobroker.hm-rega/main.js:1376:16)
2023-03-31 20:24:54.338 - error: host.ioBrokerTestsystem Caught by controller[0]: at Object.ready (/opt/iobroker/node_modules/iobroker.hm-rega/main.js:386:17)
2023-03-31 20:24:54.339 - error: host.ioBrokerTestsystem instance system.adapter.hm-rega.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-31 20:24:54.340 - info: host.ioBrokerTestsystem Restart adapter system.adapter.hm-rega.0 because enabled
2023-03-31 20:24:54.341 - warn: host.ioBrokerTestsystem Do not restart adapter system.adapter.hm-rega.0 because restart loop detected
```

**Versions:**

    hm-rpc version: v1.15.16
    hm-rega version: 3.0.46
    JS-Controller version: 5.0.1-alpha.0-20230330-e0b409fe
    Node version: v18.15.0
    Operating system:
    CCU model: raspberrymatic
    CCU firmware: 3.67.10.20230225
