### ISSUE TITLE
[bug]: After update js-controller to 7.0.0 mqtt broker adapter doesn't load

### ISSUE THREAD

**Issue by paveltsytovich** [ioBroker/ioBroker.js-controller#2939]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

After update js-controller to 7.0.0 version I see in log:
<html>
<body>

2024-10-11 08:49:54.216 - error: host.Krakow Caught by controller[0]: node:internal/modules/cjs/loader:1143
--
2024-10-11 08:49:54.216 - error: host.Krakow Caught by controller[0]: throw err;
2024-10-11 08:49:54.217 - error: host.Krakow Caught by controller[0]: ^
2024-10-11 08:49:54.218 - error: host.Krakow Caught by controller[0]: Error: Cannot find module '@iobroker/adapter-core'
2024-10-11 08:49:54.218 - error: host.Krakow Caught by controller[0]: Require stack:
2024-10-11 08:49:54.218 - error: host.Krakow Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.mqtt/main.js
2024-10-11 08:49:54.219 - error: host.Krakow Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
2024-10-11 08:49:54.219 - error: host.Krakow Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:981:27)
2024-10-11 08:49:54.220 - error: host.Krakow Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1231:19)
2024-10-11 08:49:54.221 - error: host.Krakow Caught by controller[0]: at require (node:internal/modules/helpers:177:18)
2024-10-11 08:49:54.221 - error: host.Krakow Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.mqtt/main.js:3:15)
2024-10-11 08:49:54.222 - error: host.Krakow Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1364:14)
2024-10-11 08:49:54.222 - error: host.Krakow Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
2024-10-11 08:49:54.222 - error: host.Krakow Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1203:32)
2024-10-11 08:49:54.223 - error: host.Krakow Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1019:12)
2024-10-11 08:49:54.244 - error: host.Krakow Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
2024-10-11 08:49:54.244 - error: host.Krakow Caught by controller[0]: code: 'MODULE_NOT_FOUND',
2024-10-11 08:49:54.245 - error: host.Krakow Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.mqtt/main.js' ]
2024-10-11 08:49:54.245 - error: host.Krakow Caught by controller[0]: }
2024-10-11 08:49:54.245 - error: host.Krakow Caught by controller[0]: Node.js v18.20.4
2024-10-11 08:49:54.246 - error: host.Krakow instance system.adapter.mqtt.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

</body>
</html>

### Reproduction instruction

simple perform update js-controller to 7.0.0 and start iobroker

### JS-controller version

7.0.0

### Node version

18.20.4

**Comment by paveltsytovich** [comment]
6.1.2 - last version of mqtt broker

**Comment by Apollon77** [comment]
Please try to reinstall the adapter. it seems that something is strange in your npm tree
